package RSBot.Quests;

import org.osbot.rs07.api.model.NPC;
import org.osbot.rs07.api.model.RS2Object;
import org.osbot.rs07.api.map.Position;
import org.osbot.rs07.script.ScriptManifest;
import org.osbot.rs07.script.Script;

@ScriptManifest(author = "Boomerwangs", name = "Romeo", info = "Walking to Lumby", version = 0.1, logo = "")
public class Romeo extends Script
{
	 public int onLoop() throws InterruptedException {
		 final Position RJ1 = new Position(3157, 3426, 1);
         this.walking.webWalk(new Position[] { RJ1 });
         final NPC juliet = (NPC)this.npcs.closest(new String[] { "Juliet" });
         juliet.interact(new String[] { "Talk-to" });
         sleep((long)random(2000, 3000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().selectOption(1);
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().selectOption(1);
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         final Position romeo1 = new Position(3208, 3425, 0);
         this.walking.webWalk(new Position[] { romeo1 });
         sleep((long)random(2500, 3500));
         final NPC romeo2 = (NPC)this.npcs.closest(new String[] { "Romeo" });
         romeo2.interact(new String[] { "Talk-to" });
         sleep((long)random(2000, 3000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().selectOption(4);
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         final Position father1 = new Position(3255, 3482, 0);
         this.walking.webWalk(new Position[] { father1 });
         sleep((long)random(2000, 4000));
         final NPC fatherLawrence = (NPC)this.npcs.closest(new String[] { "Father Lawrence" });
         fatherLawrence.interact(new String[] { "Talk-to" });
         sleep((long)random(2000, 3000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(8000, 10000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         final Position berry1 = new Position(3298, 3381, 0);
         this.walking.webWalk(new Position[] { berry1 });
         sleep((long)random(1000, 2000));
         final Position berry2 = new Position(3292, 3355, 0);
         this.walking.webWalk(new Position[] { berry2 });
         sleep((long)random(1000, 2000));
         final Position berry3 = new Position(3268, 3368, 0);
         this.walking.webWalk(new Position[] { berry3 });
         sleep((long)random(1000, 2000));
         ((RS2Object)this.objects.closest(new String[] { "Cadava bush" })).interact(new String[] { "Pick-from" });
         sleep((long)random(5000, 7000));
         final Position apot = new Position(3196, 3404, 0);
         this.walking.webWalk(new Position[] { apot });
         sleep((long)random(2000, 3000));
         final NPC apothecary = (NPC)this.npcs.closest(new String[] { "Apothecary" });
         apothecary.interact(new String[] { "Talk-to" });
         sleep((long)random(2000, 3000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().selectOption(2);
         sleep((long)random(2400, 3500));
         this.getDialogues().selectOption(1);
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(2000, 3000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         final Position juliet2 = new Position(3157, 3426, 1);
         this.walking.webWalk(new Position[] { juliet2 });
         sleep((long)random(2000, 3000));
         final NPC jjuliet = (NPC)this.npcs.closest(new String[] { "Juliet" });
         jjuliet.interact(new String[] { "Talk-to" });
         sleep((long)random(2000, 3000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(2000, 3000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(1000, 2000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(1000, 2000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(1000, 2000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(1000, 2000));
         final Position romeo3 = new Position(3208, 3428, 0);
         this.walking.webWalk(new Position[] { romeo3 });
         sleep((long)random(2000, 4000));
         final NPC rromeo = (NPC)this.npcs.closest(new String[] { "Romeo" });
         rromeo.interact(new String[] { "Talk-to" });
         sleep((long)random(2000, 3000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(3000, 4000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(8000, 10000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(8000, 10000));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         this.getDialogues().clickContinue();
         sleep((long)random(2400, 3500));
         sleep((long)random(3000, 4000));
     
     return 500;
 }
}
